name: PR Linting

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  super-lint:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: 'gemini/sample-apps/finance-advisor-spanner/.*\.sql'
          LOG_LEVEL: WARN
          SHELLCHECK_OPTS: -e SC1091 -e 2086
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHANGED_FILES: true
          PYTHON_PYINK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_CHECKOV: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false

  notebook-lint:
    name: Notebook Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/notebook_linter/requirements.txt
          
      - name: Run notebook linter
        run: bash .github/workflows/notebook_linter/run_linter.sh -t 